### PR TITLE
hkdf: upgrade to pre-release upstream crates

### PR DESCRIPTION
**Pull request by tarcieri**
Updates the `digest` and `hmac` crates to the new (2018 edition) upstream crates (v0.9.0-pre and v0.8.0-pre respectively).

### CODE REVIEW

**Comment by tarcieri** [comment]
I'll be cutting a final release of these soon if you'd like to hold off until then.

**Comment by vladikoff** [comment]
The ci needs to be tweaked 
image

**Comment by tarcieri** [comment]
Tests are failing because MSRV is 1.41 for these crates. I'll go ahead and remove 1.21 from the Travis config.

**Comment by tarcieri** [comment]
It's green now.

I'd also be happy to do a 2018 edition upgrade for this crate too (I just did it for all of the other RustCrypto crates)

**Comment by vladikoff** [comment]
>I'd also be happy to do a 2018 edition upgrade for this crate too 

that would be useful! 👍

**Comment by tarcieri** [comment]
Opened #32 with a 2018 edition update.

Will go ahead and merge this then rebase #32.

**Comment by tarcieri** [comment]
> Are we committing to not release a new HKDF until after we can update the dependencies again to point at non-prerelease digest and hmac, etc?

Yes, although I plan on cutting final releases of the other crates later this week, if that's ok.

Mostly I'm just trying to get all of the crates updated to the new `RustCrypto/traits` and so forth to suss out any potential showstoppers before cutting a final release.

**Pull request merged**
